services:
  - type: web
    name: reachinbox-api-tanmay
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    autoDeployTrigger: commit
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: reachinbox-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: reachinbox-redis
          property: connectionString
      - key: WEB_ORIGIN
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        sync: false
      - key: SLACK_CLIENT_ID
        sync: false
      - key: SLACK_CLIENT_SECRET
        sync: false
      - key: SLACK_CALLBACK_URL
        sync: false
      - key: ETHEREAL_USER
        sync: false
      - key: ETHEREAL_PASS
        sync: false
      - key: WORKER_CONCURRENCY
        value: "5"
      - key: MIN_SEND_INTERVAL_MS
        value: "2000"
      - key: MAX_EMAILS_PER_HOUR_PER_SENDER
        value: "200"

  - type: keyvalue
    name: reachinbox-redis
    plan: free
    region: singapore
    ipAllowList: []
    maxmemoryPolicy: noeviction
    persistenceMode: off

databases:
  - name: reachinbox-postgres
    plan: free
    region: singapore
    databaseName: reachinbox
    user: reachinbox
    postgresMajorVersion: "16"
    ipAllowList: []
